"""add language to comments

Revision ID: f4016275bf6e
Revises: 8a82008f26df
Create Date: 2018-02-23 20:19:17.883381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4016275bf6e'
down_revision = '8a82008f26df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'language')
    # ### end Alembic commands ###
