from datetime import datetime
from flask import render_template, flash, redirect, url_for, request, g, jsonify, current_app  # g variable is specific to each request and each client
from flask_login import current_user, login_required
from flask_babel import _, get_locale
from guess_language import guess_language
from app import db
from app.main.forms import EditProfileForm, CommentForm, SearchForm
from app.models import User, Comment
from app.translate import translate
from app.main import bp


@bp.before_request
def before_request():
    # The @before_request decorator registers the decorated function to be executed right before every view function in the application.
    if current_user.is_authenticated:
        current_user.last_seen = datetime.utcnow()
        db.session.commit()
        g.search_form = SearchForm()
    g.locale = str(get_locale())    # So packages such as 'moment' can support multilanguage (added in the scripts block template).

    
@bp.route('/', methods=['GET', 'POST'])
@bp.route('/index/', methods=['GET', 'POST'])
@login_required
def index():
    form = CommentForm()

    # Handle form submission (POST):
    if form.validate_on_submit():
        language = guess_language(form.comment.data)
        if language == 'UNKNOWN' or len(language) > 5:
            language = ''
        comment = Comment(body=form.comment.data, author=current_user, language=language)
        db.session.add(comment)
        db.session.commit()
        flash(_('Your comment is now live!'))
        return redirect(url_for('main.index'))  # It is a common practice to respond to a POST request generated by a web form submission with a redirect (Comment/Redirect/Get pattern).

    # Display comments (GET):
    page = request.args.get('page', 1, type=int)
    comments = current_user.followed_comments().paginate(page, current_app.config['POSTS_PER_PAGE'], False) # The 'paginate()' method returns a Pagination object.
    next_url = url_for('main.index', page=comments.next_num) if comments.has_next else None
    prev_url = url_for('main.index', page=comments.prev_num) if comments.has_prev else None
    return render_template('index.html', title=_('Home'), form=form, comments=comments.items,
        next_url=next_url, prev_url=prev_url)


@bp.route('/explore/')
@login_required
def explore():
    page = request.args.get('page', 1, type=int)
    comments = ( Comment.query.order_by(Comment.timestamp.desc()).
        paginate(page, current_app.config['POSTS_PER_PAGE'], False) )
    next_url = url_for('main.explore', page=comments.next_num) if comments.has_next else None
    prev_url = url_for('main.explore', page=comments.prev_num) if comments.has_prev else None
    return render_template('index.html', title=_('Explore'), comments=comments.items,
        next_url=next_url, prev_url=prev_url)


@bp.route('/user/<username>/')
@login_required
def user(username):
    user = User.query.filter_by(username=username).first_or_404()
    page = request.args.get('page', 1, type=int)
    comments = user.comments.order_by(Comment.timestamp.desc()).paginate(
        page, current_app.config['POSTS_PER_PAGE'], False)
    next_url = url_for('main.user', username=user.username, page=comments.next_num) if comments.has_next else None
    prev_url = url_for('main.user', username=user.username, page=comments.prev_num) if comments.has_prev else None
    return render_template('user.html', user=user, comments=comments.items,
        next_url=next_url, prev_url=prev_url)


@bp.route('/editprofile/', methods=['GET', 'POST'])
@login_required
def editprofile():
    form = EditProfileForm(current_user.username)
    if form.validate_on_submit():
        current_user.username = form.username.data
        current_user.about_me = form.about_me.data
        db.session.commit()
        flash(_('Your changes have been saved.'))
        return redirect(url_for('main.editprofile'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.about_me.data = current_user.about_me
    return render_template('editprofile.html', title=_('Edit Profile'),
                           form=form)


@bp.route('/follow/<username>/')
@login_required
def follow(username):
    user = User.query.filter_by(username=username).first()
    if user is None:
        flash(_('User %(username)s not found.', username=username))
        return redirect(url_for('main.index'))
    if user == current_user:
        flash(_('You cannot follow yourself!'))
        return redirect(url_for('main.user', username=username))
    current_user.follow(user)
    db.session.commit()
    flash(_('You are following %(username)s!', username=username))
    return redirect(url_for('main.user', username=username))


@bp.route('/unfollow/<username>/')
@login_required
def unfollow(username):
    user = User.query.filter_by(username=username).first()
    if user is None:
        flash(_('User %(username)s not found.', username=username))
        return redirect(url_for('main.index'))
    if user == current_user:
        flash(_('You cannot unfollow yourself!'))
        return redirect(url_for('main.user', username=username))
    current_user.unfollow(user)
    db.session.commit()
    flash(_('You are not following %(username)s.', username=username))
    return redirect(url_for('main.user', username=username))


# Online translation using Azure services.
@bp.route('/translate', methods=['POST'])
@login_required
def translate_text():
    return jsonify({'text': translate(request.form['text'],
                                      request.form['source_language'],
                                      request.form['dest_language'])})


# Full-text search
@bp.route('/search')
@login_required
def search():
    # I can't use here form.validate_on_submit(), as that only works with POST.
    if not g.search_form.validate():
        return redirect(url_for('main.explore'))
    page = request.args.get('page', 1, type=int)
    comments, total = Comment.search(g.search_form.q.data, page,
                               current_app.config['POSTS_PER_PAGE'])
    next_url = url_for('main.search', q=g.search_form.q.data, page=page + 1) \
        if total > page * current_app.config['POSTS_PER_PAGE'] else None
    prev_url = url_for('main.search', q=g.search_form.q.data, page=page - 1) \
        if page > 1 else None
    return render_template('search.html', title=_('Search'), comments=comments, next_url=next_url, prev_url=prev_url)
